{'data': 
	{
        'info': "Bulgaria's spectacular mountains, golden beaches and vibrant cities have begun attracting hordes of eager-eyed tourists over the past few years. As a result, beautiful ski and beach resorts are expanding quickly.The main cities have shrugged off the weary Communist-era image and have become vibrant and attractive, with a string of cultural attractions, varied shopping and lively nightlife keeping visitors entertained. In contrast, many towns and villages have preserved the authentic Bulgarian spirit and hospitality -  the country is especially proud of its rich folklore traditions.", 
	    'image_url': 'https://www.worldtravelguide.net/wp-content/uploads/2017/08/shu-Bulgaria-Sofia-525987913-TakashiImages-EDITORIALUSEONLY-1440x823.jpg', 			 
        'country_images': [
            {'imageUrl': 'https://www.worldtravelguide.net/wp-content/themes/wtg/images/main-banner1.jpg', 'title': ''}, 
            {'imageUrl': 'https://worldtravelguide.net/sites/default/files/new-images/753x320/bulgarias-ski-resorts-are-1234_0.jpg', 'title': "Bulgaria's ski resorts are growing fast"},
            {'imageUrl': 'https://worldtravelguide.net/sites/default/files/new-images/753x320/go-hiking-in-bulgarias-pi-1231_0.jpg', 'title': "Go hiking in Bulgaria's Pirin mountains"}, 
            {'imageUrl': 'https://worldtravelguide.net/sites/default/files/new-images/753x320/bulgarias-sunny-coastline-1228_0.jpg', 'title': "Bulgaria's sunny coastline"}, {'imageUrl': 'https://worldtravelguide.net/sites/default/files/new-images/753x320/traditional-dress-bulgari-1225_0.jpg', 'title': 'Traditional dress, Bulgaria'}, {'imageUrl': 'https://worldtravelguide.net/sites/default/files/new-images/753x320/ivan-vazov-national-theat-1222_0.jpg', 'title': 'Ivan Vazov National Theatre, Sofia'}]
        }
}

 [{'name': 'Sofia, Bulgaria, Sofia City Province', 'id': 7448, 'image_url': 'https://www.worldtravelguide.net/wp-content/uploads/2017/08/shu-Bulgaria-Sofia-525987913-TakashiImages-EDITORIALUSEONLY-1440x823.jpg'}, {'name': 'Sofia Capital Municipality, Bulgaria, Sofia City Province', 'id': 133813, 'image_url': 'https://www.worldtravelguide.net/wp-content/uploads/2017/08/shu-Bulgaria-Sofia-525987913-TakashiImages-EDITORIALUSEONLY-1440x823.jpg'}]
{'data': {'info': 'Since emerging from decades of civil unrest, Colombia has established itself as one of the world’s top destinations. And rightly so: this exquisite South American nation is blessed with natural beauty – think high Andean peaks, Caribbean beaches, pristine Amazon jungle – not to mention mysterious archaeological sites, colonial treasures and thriving cities. It’s a joy to travel around.At the heart of it all is Bogota, the pulsating capital. Once synonymous with drug cartels and gangs, the city has recast itself as one of South America’s trendiest destinations; a place of hip bars and street art, vibrant markets and colourful architecture. Sprawled across the Andean plateau, Bogota offers a fabulous mix of old and new; the cobbled streets of La Candelaria offer a stark contrast to the urban chic of Zona Rosa. But it works.', 'image_url': 'https://www.worldtravelguide.net/wp-content/uploads/2017/04/Think-Colombia-Bogota-178015742-DC_Colombia-copy.jpg', 'country_images': [{'imageUrl': 'https://www.worldtravelguide.net/wp-content/themes/wtg/images/main-banner1.jpg', 'title': ''}, {'imageUrl': 'https://worldtravelguide.net/sites/default/files/new-images/753x320/blue-skies-in-bogota-colo-1748.jpg', 'title': 'Blue skies in Bogota, Colombia'}, {'imageUrl': 'https://worldtravelguide.net/sites/default/files/new-images/753x320/cityscape-of-cartagena-co-1745.jpg', 'title': 'Cityscape of Cartagena Columbia at dusk'}, {'imageUrl': 'https://worldtravelguide.net/sites/default/files/new-images/753x320/cabo-san-juan-tayrona-nat-1742.jpg', 'title': 'Cabo San Juan, Tayrona National Park, Colombia'}, {'imageUrl': 'https://worldtravelguide.net/sites/default/files/new-images/753x320/bogota-colombia-1739.jpg', 'title': 'Bogota, Colombia'}, {'imageUrl': 'https://worldtravelguide.net/sites/default/files/new-images/753x320/bogota-colombia-1736.jpg', 'title': 'Bogota, Colombia'}]}}
RESULTS [{'name': 'Sofia, Bulgaria, Sofia City Province', 'id': 7448, 'image_url': 'https://www.worldtravelguide.net/wp-content/uploads/2017/08/shu-Bulgaria-Sofia-525987913-TakashiImages-EDITORIALUSEONLY-1440x823.jpg'}, {'name': 'Sofia Capital Municipality, Bulgaria, Sofia City Province', 'id': 133813, 'image_url': 'https://www.worldtravelguide.net/wp-content/uploads/2017/08/shu-Bulgaria-Sofia-525987913-TakashiImages-EDITORIALUSEONLY-1440x823.jpg'}, {'name': 'Santa Sofía, Colombia, Boyacá Department', 'id': 3639888, 'image_url': 'https://www.worldtravelguide.net/wp-content/uploads/2017/04/Think-Colombia-Bogota-178015742-DC_Colombia-copy.jpg'}]
{'data': {'info': 'Since emerging from decades of civil unrest, Colombia has established itself as one of the world’s top destinations. And rightly so: this exquisite South American nation is blessed with natural beauty – think high Andean peaks, Caribbean beaches, pristine Amazon jungle – not to mention mysterious archaeological sites, colonial treasures and thriving cities. It’s a joy to travel around.At the heart of it all is Bogota, the pulsating capital. Once synonymous with drug cartels and gangs, the city has recast itself as one of South America’s trendiest destinations; a place of hip bars and street art, vibrant markets and colourful architecture. Sprawled across the Andean plateau, Bogota offers a fabulous mix of old and new; the cobbled streets of La Candelaria offer a stark contrast to the urban chic of Zona Rosa. But it works.', 'image_url': 'https://www.worldtravelguide.net/wp-content/uploads/2017/04/Think-Colombia-Bogota-178015742-DC_Colombia-copy.jpg', 'country_images': [{'imageUrl': 'https://www.worldtravelguide.net/wp-content/themes/wtg/images/main-banner1.jpg', 'title': ''}, {'imageUrl': 'https://worldtravelguide.net/sites/default/files/new-images/753x320/blue-skies-in-bogota-colo-1748.jpg', 'title': 'Blue skies in Bogota, Colombia'}, {'imageUrl': 'https://worldtravelguide.net/sites/default/files/new-images/753x320/cityscape-of-cartagena-co-1745.jpg', 'title': 'Cityscape of Cartagena Columbia at dusk'}, {'imageUrl': 'https://worldtravelguide.net/sites/default/files/new-images/753x320/cabo-san-juan-tayrona-nat-1742.jpg', 'title': 'Cabo San Juan, Tayrona National Park, Colombia'}, {'imageUrl': 'https://worldtravelguide.net/sites/default/files/new-images/753x320/bogota-colombia-1739.jpg', 'title': 'Bogota, Colombia'}, {'imageUrl': 'https://worldtravelguide.net/sites/default/files/new-images/753x320/bogota-colombia-1736.jpg', 'title': 'Bogota, Colombia'}]}}
R